name: Release and deploy

# when a release is made with the tag pattern release-v*.*.*
# on:
#   release:
#     tags: ["release-v*.*.*"]

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-gh-pages:
    name: Build github pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build docs
        run: pnpm run pitsby:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pitsby

      # - name: Prepare tag
      #   id: prepare_tag
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     echo "DEPLOY_TAG_NAME=deploy-${TAG_NAME}" >> "${GITHUB_OUTPUT}"

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
      #     tag_message: 'Deployment ${{ github.ref_name }}'
        